version: '3.7' # composeファイルのバーション指定
volumes:
  db-store:
services:
  golang: 
    tty: true
    build: ./docker/go
    depends_on:
      - db
    volumes:
      - ./backend:/go/src/app
      - ./docker/go/pkg:/go/src/github.com
      
    ports:
      - "3000"         
    command: bash -c "realize start --server"
    networks:
      - default

  nginx:
    build: ./docker/nginx
    ports:
      - "8090:80"
    depends_on:
      - "golang"
      - "vue"
    networks:
      - default
   
  vue:
    build: ./Docker/vue
    ports:
        - "7060:8080"
    volumes:
        - ./vue:/vue/src/app/
    tty: true
    stdin_open: true
    command: /bin/sh
    networks:
      - default
  db:
    build: ./docker/mysql
    container_name: app_db
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3367:3306
    networks:
      - default