version: '3' # composeファイルのバーション指定
services:
  golang: 
    tty: true
    build: ./docker/go
    volumes:
      - ./backend:/go/src/app
    ports:
      - "3000"         
    command: bash -c "realize start --server"

  nginx:
    build: ./docker/nginx
    ports:
      - "8090:80"
    depends_on:
      - "golang"
      - "vue"
    networks:
      - default
   
  vue:
    build: ./Docker/vue
    ports:
        - "7060:8080"
    volumes:
        - ./vue:/vue/src/app/
    tty: true
    stdin_open: true
    command: /bin/sh